--this source code was auto-generated by xls2lua.exe, do not modify it

local LOGIN_CHEST_POOL_DATA=
{
	EVar = 
	{
		type_n=1,--"宝箱种类"
	},
	[1]={101},
	[2]={101},
	[3]={101},
	[4]={101},
	[5]={101},
	[6]={101},
}
return LOGIN_CHEST_POOL_DATA
