--this source code was auto-generated by xls2lua.exe, do not modify it

local TASK_RANK_DATA=
{
	EVar = 
	{
		trophy_n=1,--"奖杯数量"
	},
	[1]={0},
	[2]={30},
	[3]={150},
	[4]={5000},
	[5]={5000},
	[6]={5000},
	[7]={5000},
}
return TASK_RANK_DATA
