--this source code was auto-generated by xls2lua.exe, do not modify it

local TASK_DATA=
{
	EVar = 
	{
		type_n=1,--"任务类型;1=人头任务;2=每日任务;3=积分任务;4=成就任务"
		title_s=2,--"标题"
		desc_s=3,--"描述"
		icon_s=4,--"图标"
		prerequisite_n=5,--"前置任务ID"
		obj_id_n=6,--"目标ID;1=在竞技场x击杀敌方玩家y次;2=赢得对战x次;3=最大奖杯数达到x;4=本地排行榜达到x名;5=首次更换头像;101=生成小炸弹x次;102=生成大炸弹x次;201=生成横排火箭x次;202=生成竖排火箭x次;203=生成十字火箭x次;204=生成彩色十字火箭x次;301=生成迪斯科球x次"
		obj_param_table_repeated2=7,--
		obj_amount_n=8,--"数量"
		display_pattern_n=9,--"进度条数量显示模式;0=真实数量;1=固定0/1"
		chest_id_n=10,--"宝箱id"
		chest_type_n=11,--"宝箱类型"
		task_point_n=12,--"任务积分"
		page_name_s=13,--"成就跳转界面"
	},
	[121000101]={1,"D_TaskTitle1","D_TaskDesc1","C0ic063",0,1,{-1},30,0,0,106,0,""},
	[124000101]={4,"D_TaskTitle2","D_TaskDesc2","C0ic063",0,2,{},8,0,112020001,0,0,"SelectArenaPanel"},
	[124000102]={4,"D_TaskTitle2","D_TaskDesc2","C0ic063",124000101,2,{},25,0,113020200,0,0,"SelectArenaPanel"},
	[124000103]={4,"D_TaskTitle2","D_TaskDesc2","C0ic063",124000102,2,{},75,0,113020300,0,0,"SelectArenaPanel"},
	[124000104]={4,"D_TaskTitle2","D_TaskDesc2","C0ic063",124000103,2,{},200,0,113020400,0,0,"SelectArenaPanel"},
	[124000105]={4,"D_TaskTitle2","D_TaskDesc2","C0ic063",124000104,2,{},1000,0,113020500,0,0,"SelectArenaPanel"},
	[124000201]={4,"D_TaskTitle3","D_TaskDesc3","C0ic063",0,3,{},8,0,112020002,0,0,"SelectArenaPanel"},
	[124000202]={4,"D_TaskTitle3","D_TaskDesc3","C0ic063",124000201,3,{},100,0,112020003,0,0,"SelectArenaPanel"},
	[124000203]={4,"D_TaskTitle3","D_TaskDesc3","C0ic063",124000202,3,{},300,0,113020200,0,0,"SelectArenaPanel"},
	[124000204]={4,"D_TaskTitle3","D_TaskDesc3","C0ic063",124000203,3,{},600,0,113020300,0,0,"SelectArenaPanel"},
	[124000205]={4,"D_TaskTitle3","D_TaskDesc3","C0ic063",124000204,3,{},900,0,113020400,0,0,"SelectArenaPanel"},
	[124000301]={4,"D_TaskTitle4","D_TaskDesc4","C0ic063",0,4,{},35,1,113020100,0,0,"PVPRankListPanel"},
	[124000302]={4,"D_TaskTitle4","D_TaskDesc4","C0ic063",124000201,4,{},25,1,113020200,0,0,"PVPRankListPanel"},
	[124000303]={4,"D_TaskTitle4","D_TaskDesc4","C0ic063",124000202,4,{},15,1,113020300,0,0,"PVPRankListPanel"},
	[124000304]={4,"D_TaskTitle4","D_TaskDesc4","C0ic063",124000203,4,{},5,1,113020400,0,0,"PVPRankListPanel"},
	[124000305]={4,"D_TaskTitle4","D_TaskDesc4","C0ic063",124000204,4,{},1,1,112020004,0,0,"PVPRankListPanel"},
	[124000401]={4,"D_TaskTitle5","D_TaskDesc5","C0ic063",124000204,5,{},1,0,113020100,0,0,"PVPUserInfoPanel"},
}
return TASK_DATA
